spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://139.224.113.89:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: 139.224.113.89:8848
    alicloud:
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
      access-key: LTAI4GCsXw7uLhp5rtYrcgBq
      secret-key: camw3wVZ2LyEaQxmtHMRoK3yVyfXaW
  application:
    name: gulimall-product
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 12000
