spring:
  cloud:
    nacos:
      discovery:
        server-addr: 139.224.113.89:8848
      config:
        timeout: 30000
    gateway:
      routes:
        - id: product-route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: thridparty-route
          uri: lb://gulimall-thrid-party
          predicates:
            - Path=/api/thridparty/**
          filters:
            - RewritePath=/api/thridparty/(?<segment>/?.*), /$\{segment}

        - id: member-route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: ware-route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: gulimall_auth-route
          uri: lb://gulimall-auth
          predicates:
            - Host=auth.gulimall.com

        - id: gulimall_search_route
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com

        - id: gulimall-cart_route
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com

        - id: gulimall-order_router
          uri: lb://gulimall-order
          predicates:
            - Host=order.gulimall.com

        - id: gulimall-member_router
          uri: lb://gulimall-member
          predicates:
            - Host=member.gulimall.com

        - id: gulimall-seckill
          uri: lb://gulimall-seckill
          predicates:
            - Host=seckill.gulimall.com

        - id: gulimall_host_route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com

        - id: admin-route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

  application:
    name: gulimall-gateway
server:
  port: 8800
