spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: baidu
          uri: http://www.baidu.com
          predicates:
          - Query=url,baidu
        - id: qq
          uri: http://www.qq.com
          predicates:
          - Query=url,qq
  application:
    name: gulimall-gateway
server:
  port: 88
